# Generated by Django 3.1.6 on 2021-03-08 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='author',
            new_name='user',
        ),
    ]
